### ISSUE TITLE
DwengoBlockly 2.0 Arduino IDE hangs

### ISSUE THREAD

**Issue by kakila** [dwengovzw/Blockly-for-Dwenguino#10]
After following instructions on [web](https://dwengo.org/2019/07/17/1175/) plugin installs correctly.
However when launching from Arduino IDE 1.8.3 I get

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: The time is invalid.
	at javafx.animation.KeyFrame.<init>(KeyFrame.java:189)
	at javafx.animation.KeyFrame.<init>(KeyFrame.java:226)
	at javafx.scene.Scene$ClickCounter.start(Scene.java:3380)
	at javafx.scene.Scene$ClickCounter.access$7400(Scene.java:3335)
	at javafx.scene.Scene$ClickGenerator.preProcess(Scene.java:3430)
	at javafx.scene.Scene$ClickGenerator.access$7900(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3738)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$293(EmbeddedScene.java:256)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$294(EmbeddedScene.java:244)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

At this point the application hangs and must be killed.

Arduino IDE: 1.8.3
DwengoBlockly: 2.0
Dwenguino library: 2.2.1
OS:
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13

**Comment by ptheoch** [comment]
Hi Juan Pablo,
As I am also using Debian stable, I will try to reproduce the problem and respond by the end of the week.

**Comment by tomneutens** [comment]
The version of DwenguinoBlockly which runs as a plugin for the Arduino IDE has been deprecated. We had too many issues with the Arduino IDE and the limited documentation for writing plugins. We have switched to standalone and online environments. The standalone version uses electron to display the web environment. On the backend we use a nodejs server to send code to the microcontroller. The nodejs server uses make to compile the code and upload the hex file to the Dwenguino board. For now the installation is only supported on Linux (tested on ubuntu 18.04). However, if you have a binary of make for your platform you should be able to install it and replace the ubuntu make binary with the binary for your platform.
The latest code can be found in the dwenguinoblockly-standalone branch.
For now there is no option to edit de textual code however, we plan to add this in the future.

**Comment by kakila** [comment]
Thanks for the answer.
I will check that.

If the plungin is deprecated this should be clearly stated in the dwengo website (the tutorial is there without any warning). USers of mine are still installing that and Ardublocks! And the bad experience only makes them less convinced of using dwenguino.

**Comment by tomneutens** [comment]
Stopped supporting Arduino IDE. All in browser now.
