### ISSUE TITLE
Uploading social robot scenario to the simulator is broken.

### ISSUE THREAD

**Issue by tomneutens** [dwengovzw/Blockly-for-Dwenguino#81]
No details yet, just doesn't work.
Stack trace:
dwenguinoblockly.bundle.js:2 TypeError: He.uploadXml is not a function
    at e.<anonymous> (dwenguinoblockly.bundle.js:2:3700650)
    at d (dwenguinoblockly.bundle.js:2:1157)
    at Generator._invoke (dwenguinoblockly.bundle.js:2:945)
    at Generator.next (dwenguinoblockly.bundle.js:2:1582)
    at Be (dwenguinoblockly.bundle.js:2:3697407)
    at r (dwenguinoblockly.bundle.js:2:3700970)
    at dwenguinoblockly.bundle.js:2:3701031
    at new Promise (<anonymous>)
    at e.s (dwenguinoblockly.bundle.js:2:3700910)
    at e.n.value (dwenguinoblockly.bundle.js:2:3701065)
    at HTMLDivElement.<anonymous> (dwenguinoblockly.bundle.js:2:3703919)
    at HTMLDivElement.dispatch (dwenguinoblockly.bundle.js:2:795541)
    at HTMLDivElement.m.handle (dwenguinoblockly.bundle.js:2:793536)

**Comment by tomneutens** [comment]
Somehow the function uploadTextFile in file_io_controller.js was changed from uploadXml. In dwenguino_scenario_utils.js the uploadXml function was still called. Consequently, it did not exist. Changed it to uploadTextFile.
